# Generated by Django 5.2.8 on 2025-11-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon',
            name='SerialNumber',
            field=models.IntegerField(),
        ),
    ]
