# Generated by Django 5.2.8 on 2025-11-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amazon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=40)),
                ('SerialNumber', models.IntegerField()),
                ('Brand', models.CharField()),
                ('Price', models.IntegerField()),
                ('ManufacturingDate', models.DateField()),
                ('ExpiryDate', models.DateField()),
                ('Rating', models.IntegerField()),
            ],
        ),
    ]
